project_id = "mrjftwvygqoimexwgclm"

[functions.invite-teacher]
verify_jwt = true

[functions.invite-guardian]
verify_jwt = true

[functions.invite-student]
verify_jwt = true

[functions.request-plan-change]
verify_jwt = true