-- Push notifications são disparadas directamente pelo frontend via supabase.functions.invoke("notifications-push").
-- Não é necessário trigger SQL — o helper sendNotificationWithPush.ts trata de inserir + chamar push.
-- Este ficheiro mantém-se vazio para não quebrar a sequência de migrações.
