// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { authSessionStorage } from '@/lib/authSessionStorage';
import { createSupabaseFetch } from '@/lib/supabaseFetch';
import type { Database } from './types';

const SUPABASE_URL = "https://mrjftwvygqoimexwgclm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yamZ0d3Z5Z3FvaW1leHdnY2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwNTk3MzEsImV4cCI6MjA5MjYzNTczMX0.VzhclH9Pc4QGiCkOexoK2563IXCy1l97RxUjnTF-8oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(),
  },
  auth: {
    /** `authSessionStorage` liberta quota se o cache TanStack persistido encher o localStorage. */
    storage: authSessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});